import type { Metadata } from "next";
import { Homemade_Apple, Inter } from "next/font/google";
import "./globals.css";
import { Button, Dropdown, IconButton, Menu, MenuButton, MenuItem } from "@mui/joy";
import Link from "next/link";
import { GoHome } from "react-icons/go";
import { BiEdit, BiPaperPlane } from "react-icons/bi";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JSON Editor",
  description: "Generated by create next app and juju",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Dropdown>
      <MenuButton>
        <Link className="m-2" href={"/"}><GoHome></GoHome><p>Home</p></Link>
        
      </MenuButton>
      <MenuButton>
        <Link className="m-2" href={"/editor"}><BiEdit></BiEdit><p>Editor</p></Link>
        
      </MenuButton>
      <MenuButton>
        <Link className="m-2" href={"/papers"}><BiPaperPlane></BiPaperPlane><p>Papers</p></Link>
      </MenuButton>
      {/* <Menu>
        <MenuItem></MenuItem>
      </Menu> */}
      </Dropdown>
        {children}
        </body>
    </html>
  );
}
